[2025-03-24T16:20:35.982+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:20:35.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:20:35.985+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:20:35.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:20:35.990+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:20:35.988+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:20:35.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:20:36.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.043 seconds
[2025-03-24T16:21:06.153+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:21:06.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:21:06.155+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:21:06.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:21:06.158+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:21:06.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:21:06.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:21:06.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.022 seconds
[2025-03-24T16:21:36.349+0000] {processor.py:186} INFO - Started process (PID=178) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:21:36.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:21:36.360+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:21:36.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:21:36.365+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:21:36.363+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:21:36.365+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:21:36.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.039 seconds
[2025-03-24T16:22:06.536+0000] {processor.py:186} INFO - Started process (PID=183) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:22:06.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:22:06.540+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:22:06.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:22:06.543+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:22:06.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:22:06.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:22:06.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.026 seconds
[2025-03-24T16:22:36.770+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:22:36.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:22:36.772+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:22:36.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:22:36.775+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:22:36.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:22:36.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:22:36.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.021 seconds
[2025-03-24T16:23:06.973+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:23:06.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:23:06.982+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:23:06.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:23:06.985+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:23:06.984+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:23:06.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:23:06.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.029 seconds
[2025-03-24T16:23:37.181+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:23:37.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:23:37.183+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:23:37.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:23:37.185+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:23:37.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:23:37.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:23:37.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.019 seconds
[2025-03-24T16:24:07.408+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:24:07.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:24:07.410+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:24:07.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:24:07.413+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:24:07.412+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:24:07.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:24:07.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.023 seconds
[2025-03-24T16:24:37.635+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:24:37.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:24:37.646+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:24:37.645+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:24:37.651+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:24:37.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:24:37.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:24:37.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.038 seconds
[2025-03-24T16:25:07.813+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:25:07.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:25:07.816+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:25:07.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:25:07.820+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:25:07.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:25:07.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:25:07.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.033 seconds
[2025-03-24T16:25:37.997+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:25:37.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:25:37.999+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:25:37.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:25:38.001+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:25:38.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:25:38.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:25:38.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.030 seconds
[2025-03-24T16:26:08.171+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:26:08.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:26:08.173+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:26:08.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:26:08.176+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:26:08.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:26:08.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:26:08.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.022 seconds
[2025-03-24T16:26:38.364+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:26:38.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:26:38.373+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:26:38.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:26:38.376+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:26:38.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:26:38.376+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:26:38.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.028 seconds
[2025-03-24T16:27:08.518+0000] {processor.py:186} INFO - Started process (PID=233) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:27:08.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:27:08.528+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:27:08.528+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:27:08.530+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:27:08.530+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:27:08.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:27:08.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.027 seconds
[2025-03-24T16:27:38.701+0000] {processor.py:186} INFO - Started process (PID=238) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:27:38.704+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:27:38.705+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:27:38.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:27:38.708+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:27:38.707+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:27:38.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:27:38.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.023 seconds
[2025-03-24T16:28:08.872+0000] {processor.py:186} INFO - Started process (PID=243) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:28:08.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:28:08.874+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:28:08.873+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:28:08.876+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:28:08.875+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:28:08.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:28:08.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.020 seconds
[2025-03-24T16:28:39.008+0000] {processor.py:186} INFO - Started process (PID=248) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:28:39.008+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:28:39.010+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:28:39.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:28:39.012+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:28:39.012+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:28:39.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:28:39.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.026 seconds
[2025-03-24T16:29:09.185+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:29:09.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:29:09.187+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:29:09.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:29:09.190+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:29:09.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:29:09.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:29:09.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.022 seconds
[2025-03-24T16:29:39.346+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:29:39.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:29:39.348+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:29:39.348+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:29:39.351+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:29:39.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:29:39.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:29:39.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.020 seconds
[2025-03-24T16:30:09.507+0000] {processor.py:186} INFO - Started process (PID=263) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:30:09.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:30:09.519+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:30:09.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:30:09.524+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:30:09.522+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:30:09.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:30:09.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.039 seconds
[2025-03-24T16:30:39.725+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:30:39.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:30:39.735+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:30:39.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:30:39.738+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:30:39.737+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:30:39.738+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:30:39.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.033 seconds
[2025-03-24T16:31:09.932+0000] {processor.py:186} INFO - Started process (PID=273) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:31:09.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:31:09.945+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:31:09.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:31:09.951+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:31:09.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:31:09.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:31:09.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.063 seconds
[2025-03-24T16:31:40.163+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:31:40.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:31:40.175+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:31:40.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:31:40.181+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:31:40.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:31:40.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:31:40.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.058 seconds
[2025-03-24T16:32:10.436+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:32:10.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:32:10.442+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:32:10.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:32:10.448+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:32:10.446+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:32:10.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:32:10.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.057 seconds
[2025-03-24T16:32:40.672+0000] {processor.py:186} INFO - Started process (PID=288) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:32:40.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:32:40.677+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:32:40.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:32:40.683+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:32:40.681+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:32:40.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:32:40.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.051 seconds
[2025-03-24T16:33:10.926+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:33:10.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:33:10.939+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:33:10.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:33:10.945+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:33:10.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:33:10.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:33:10.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.061 seconds
[2025-03-24T16:33:41.156+0000] {processor.py:186} INFO - Started process (PID=298) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:33:41.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:33:41.169+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:33:41.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:33:41.176+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:33:41.174+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:33:41.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:33:41.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.058 seconds
[2025-03-24T16:34:11.409+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:34:11.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:34:11.411+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:34:11.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:34:11.414+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:34:11.413+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:34:11.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:34:11.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.021 seconds
[2025-03-24T16:34:41.638+0000] {processor.py:186} INFO - Started process (PID=308) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:34:41.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:34:41.640+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:34:41.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:34:41.643+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:34:41.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:34:41.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:34:41.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.022 seconds
[2025-03-24T16:35:11.856+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:35:11.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:35:11.858+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:35:11.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:35:11.861+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:35:11.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:35:11.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:35:11.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.021 seconds
[2025-03-24T16:35:42.043+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:35:42.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:35:42.044+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:35:42.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:35:42.047+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:35:42.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:35:42.047+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:35:42.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.021 seconds
[2025-03-24T16:36:12.244+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:36:12.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:36:12.255+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:36:12.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:36:12.259+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:36:12.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:36:12.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:36:12.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.033 seconds
[2025-03-24T16:36:42.455+0000] {processor.py:186} INFO - Started process (PID=328) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:36:42.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:36:42.457+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:36:42.457+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:36:42.460+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:36:42.459+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:36:42.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:36:42.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.022 seconds
[2025-03-24T16:37:12.656+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:37:12.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:37:12.667+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:37:12.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:37:12.672+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:37:12.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:37:12.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:37:12.687+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.035 seconds
[2025-03-24T16:37:42.852+0000] {processor.py:186} INFO - Started process (PID=338) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:37:42.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:37:42.855+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:37:42.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:37:42.859+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:37:42.858+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:37:42.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:37:42.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.026 seconds
[2025-03-24T16:38:13.058+0000] {processor.py:186} INFO - Started process (PID=343) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:38:13.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:38:13.062+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:38:13.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:38:13.065+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:38:13.064+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:38:13.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:38:13.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.027 seconds
[2025-03-24T16:38:43.258+0000] {processor.py:186} INFO - Started process (PID=348) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:38:43.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:38:43.267+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:38:43.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:38:43.270+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:38:43.269+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:38:43.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:38:43.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.029 seconds
[2025-03-24T16:39:13.449+0000] {processor.py:186} INFO - Started process (PID=353) to work on /opt/airflow/dags/dags.py
[2025-03-24T16:39:13.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2025-03-24T16:39:13.458+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:39:13.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2025-03-24T16:39:13.461+0000] {logging_mixin.py:190} INFO - [2025-03-24T16:39:13.460+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from pyhive import hive
ModuleNotFoundError: No module named 'pyhive'
[2025-03-24T16:39:13.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2025-03-24T16:39:13.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dags.py took 0.029 seconds
