[2025-03-21T20:49:58.895+0000] {processor.py:186} INFO - Started process (PID=3723251) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:49:58.896+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:49:58.898+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:49:58.898+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:49:58.901+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:49:58.901+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:49:58.902+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:49:58.901+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:49:58.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:49:58.907+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-03-21T20:50:59.426+0000] {processor.py:186} INFO - Started process (PID=3723964) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:50:59.435+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:50:59.438+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:50:59.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:50:59.442+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:50:59.441+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:50:59.442+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:50:59.442+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:50:59.443+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:50:59.450+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-21T20:51:53.626+0000] {processor.py:186} INFO - Started process (PID=3724697) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:51:53.627+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:51:53.630+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:51:53.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:51:53.633+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:51:53.632+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:51:53.633+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:51:53.633+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:51:53.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:51:53.639+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-03-21T20:52:49.155+0000] {processor.py:186} INFO - Started process (PID=3725282) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:52:49.163+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:52:49.165+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:52:49.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:52:49.167+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:52:49.166+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:52:49.167+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:52:49.167+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:52:49.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:52:49.172+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-03-21T20:53:41.772+0000] {processor.py:186} INFO - Started process (PID=3725913) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:53:41.781+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:53:41.784+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:53:41.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:53:41.789+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:53:41.788+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:53:41.789+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:53:41.789+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:53:41.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:53:41.797+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-21T20:54:36.485+0000] {processor.py:186} INFO - Started process (PID=3726596) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:54:36.495+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:54:36.498+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:54:36.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:54:36.502+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:54:36.502+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:54:36.503+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:54:36.503+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:54:36.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:54:36.585+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2025-03-21T20:55:27.608+0000] {processor.py:186} INFO - Started process (PID=3727219) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:55:27.616+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:55:27.618+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:55:27.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:55:27.620+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:55:27.619+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:55:27.620+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:55:27.620+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:55:27.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:55:27.626+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-03-21T20:56:18.212+0000] {processor.py:186} INFO - Started process (PID=3727928) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:56:18.221+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:56:18.225+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:56:18.224+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:56:18.228+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:56:18.227+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:56:18.228+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:56:18.228+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:56:18.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:56:18.235+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-21T20:57:10.947+0000] {processor.py:186} INFO - Started process (PID=3728731) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:57:10.956+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:57:10.958+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:57:10.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:57:10.962+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:57:10.961+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:57:10.962+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:57:10.962+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:57:10.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:57:10.969+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-21T20:58:02.751+0000] {processor.py:186} INFO - Started process (PID=3729274) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:58:02.760+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:58:02.763+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:58:02.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:58:02.768+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:58:02.767+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:58:02.768+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:58:02.768+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:58:02.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:58:02.776+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-03-21T20:59:49.259+0000] {processor.py:186} INFO - Started process (PID=3730733) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:59:49.267+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T20:59:49.270+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:59:49.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:59:49.274+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:59:49.274+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T20:59:49.275+0000] {logging_mixin.py:190} INFO - [2025-03-21T20:59:49.274+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T20:59:49.275+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T20:59:49.282+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-03-21T21:00:47.413+0000] {processor.py:186} INFO - Started process (PID=3731460) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:00:47.422+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:00:47.425+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:00:47.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:00:47.429+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:00:47.429+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:00:47.430+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:00:47.430+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:00:47.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:00:47.437+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-03-21T21:01:42.329+0000] {processor.py:186} INFO - Started process (PID=3732161) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:01:42.335+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:01:42.338+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:01:42.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:01:42.342+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:01:42.342+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:01:42.343+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:01:42.342+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:01:42.343+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:01:42.350+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-21T21:02:38.944+0000] {processor.py:186} INFO - Started process (PID=3732843) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:02:38.945+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:02:38.947+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:02:38.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:02:38.949+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:02:38.949+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:02:38.950+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:02:38.950+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:02:38.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:02:38.956+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-03-21T21:03:31.794+0000] {processor.py:186} INFO - Started process (PID=3733607) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:03:31.803+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:03:31.806+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:03:31.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:03:31.809+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:03:31.809+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:03:31.810+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:03:31.810+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:03:31.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:03:31.816+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-03-21T21:04:28.867+0000] {processor.py:186} INFO - Started process (PID=3734343) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:04:28.875+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:04:28.876+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:04:28.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:04:28.879+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:04:28.878+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:04:28.879+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:04:28.879+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:04:28.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:04:28.885+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-03-21T21:05:21.379+0000] {processor.py:186} INFO - Started process (PID=3735207) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:05:21.387+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:05:21.390+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:05:21.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:05:21.395+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:05:21.394+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:05:21.396+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:05:21.396+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:05:21.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:05:21.403+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-03-21T21:06:15.677+0000] {processor.py:186} INFO - Started process (PID=3735846) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:06:15.686+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:06:15.689+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:06:15.689+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:06:15.694+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:06:15.693+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:06:15.694+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:06:15.694+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:06:15.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:06:15.702+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-03-21T21:07:08.526+0000] {processor.py:186} INFO - Started process (PID=3737165) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:07:08.534+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:07:08.535+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:07:08.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:07:08.538+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:07:08.537+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:07:08.538+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:07:08.538+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:07:08.538+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:07:08.545+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-03-21T21:08:02.754+0000] {processor.py:186} INFO - Started process (PID=3737851) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:08:02.763+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:08:02.766+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:08:02.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:08:02.771+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:08:02.770+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:08:02.771+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:08:02.771+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:08:02.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:08:02.778+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-03-21T21:09:05.911+0000] {processor.py:186} INFO - Started process (PID=3738692) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:09:05.920+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:09:05.922+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:09:05.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:09:05.926+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:09:05.925+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:09:05.926+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:09:05.926+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:09:05.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:09:05.935+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-03-21T21:10:01.099+0000] {processor.py:186} INFO - Started process (PID=3739490) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:10:01.108+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:10:01.112+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:10:01.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:10:01.118+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:10:01.116+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:10:01.118+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:10:01.118+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:10:01.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:10:01.132+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-03-21T21:10:58.414+0000] {processor.py:186} INFO - Started process (PID=3741088) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:10:58.422+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:10:58.424+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:10:58.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:10:58.428+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:10:58.427+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:10:58.428+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:10:58.428+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:10:58.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:10:58.435+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-21T21:11:55.140+0000] {processor.py:186} INFO - Started process (PID=3742211) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:11:55.149+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:11:55.150+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:11:55.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:11:55.153+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:11:55.152+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:11:55.153+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:11:55.153+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:11:55.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:11:55.160+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-21T21:12:48.314+0000] {processor.py:186} INFO - Started process (PID=3743213) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:12:48.314+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:12:48.316+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:12:48.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:12:48.319+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:12:48.318+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:12:48.319+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:12:48.319+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:12:48.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:12:48.326+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-03-21T21:13:40.640+0000] {processor.py:186} INFO - Started process (PID=3744143) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:13:40.641+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:13:40.642+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:13:40.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:13:40.646+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:13:40.645+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:13:40.646+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:13:40.646+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:13:40.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:13:40.654+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-03-21T21:14:34.248+0000] {processor.py:186} INFO - Started process (PID=3744939) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:14:34.257+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:14:34.260+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:14:34.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:14:34.266+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:14:34.265+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:14:34.266+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:14:34.266+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:14:34.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:14:34.280+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-03-21T21:15:36.012+0000] {processor.py:186} INFO - Started process (PID=3745720) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:15:36.021+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:15:36.025+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:15:36.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:15:36.031+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:15:36.030+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:15:36.032+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:15:36.031+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:15:36.032+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:15:36.046+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-03-21T21:16:37.287+0000] {processor.py:186} INFO - Started process (PID=3746484) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:16:37.296+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:16:37.300+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:16:37.299+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:16:37.308+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:16:37.306+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:16:37.309+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:16:37.308+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:16:37.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:16:37.323+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2025-03-21T21:17:38.753+0000] {processor.py:186} INFO - Started process (PID=3747241) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:17:38.763+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:17:38.766+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:17:38.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:17:38.771+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:17:38.770+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:17:38.772+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:17:38.772+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:17:38.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:17:38.787+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-03-21T21:18:43.543+0000] {processor.py:186} INFO - Started process (PID=3748054) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:18:43.552+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:18:43.555+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:18:43.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:18:43.561+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:18:43.560+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:18:43.561+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:18:43.561+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:18:43.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:18:43.576+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-03-21T21:19:47.077+0000] {processor.py:186} INFO - Started process (PID=3748821) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:19:47.086+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:19:47.089+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:19:47.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:19:47.095+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:19:47.094+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:19:47.095+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:19:47.095+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:19:47.095+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:19:47.109+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-03-21T21:20:50.151+0000] {processor.py:186} INFO - Started process (PID=3749580) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:20:50.160+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:20:50.163+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:20:50.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:20:50.169+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:20:50.168+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:20:50.170+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:20:50.170+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:20:50.170+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:20:50.184+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-03-21T21:21:56.240+0000] {processor.py:186} INFO - Started process (PID=3750402) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:21:56.249+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:21:56.252+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:21:56.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:21:56.258+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:21:56.257+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:21:56.258+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:21:56.258+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:21:56.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:21:56.273+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-03-21T21:23:01.942+0000] {processor.py:186} INFO - Started process (PID=3751231) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:23:01.951+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:23:01.954+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:23:01.954+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:23:01.960+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:23:01.959+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:23:01.961+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:23:01.960+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:23:01.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:23:01.979+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2025-03-21T21:24:03.746+0000] {processor.py:186} INFO - Started process (PID=3751949) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:24:03.755+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:24:03.759+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:24:03.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:24:03.764+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:24:03.763+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:24:03.765+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:24:03.765+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:24:03.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:24:03.779+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-03-21T21:25:07.411+0000] {processor.py:186} INFO - Started process (PID=3752623) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:25:07.420+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:25:07.423+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:25:07.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:25:07.431+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:25:07.429+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:25:07.431+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:25:07.431+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:25:07.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:25:07.446+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2025-03-21T21:26:12.631+0000] {processor.py:186} INFO - Started process (PID=3753318) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:26:12.632+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:26:12.635+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:26:12.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:26:12.641+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:26:12.640+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:26:12.641+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:26:12.641+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:26:12.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:26:12.656+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-03-21T21:27:14.766+0000] {processor.py:186} INFO - Started process (PID=3753961) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:27:14.775+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:27:14.779+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:27:14.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:27:14.786+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:27:14.785+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:27:14.787+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:27:14.786+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:27:14.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:27:14.801+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-03-21T21:28:17.222+0000] {processor.py:186} INFO - Started process (PID=3754608) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:28:17.224+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:28:17.227+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:28:17.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:28:17.232+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:28:17.231+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:28:17.233+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:28:17.233+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:28:17.233+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:28:17.248+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-03-21T21:29:16.910+0000] {processor.py:186} INFO - Started process (PID=3755244) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:29:16.919+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:29:16.922+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:29:16.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:29:16.928+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:29:16.927+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:29:16.928+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:29:16.928+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:29:16.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:29:16.942+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-03-21T21:30:22.218+0000] {processor.py:186} INFO - Started process (PID=3755937) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:30:22.228+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:30:22.231+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:30:22.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:30:22.237+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:30:22.236+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:30:22.237+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:30:22.237+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:30:22.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:30:22.251+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-03-21T21:31:28.633+0000] {processor.py:186} INFO - Started process (PID=3756622) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:31:28.642+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:31:28.645+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:31:28.645+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:31:28.651+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:31:28.650+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:31:28.651+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:31:28.651+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:31:28.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:31:28.665+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-03-21T21:32:33.840+0000] {processor.py:186} INFO - Started process (PID=3757301) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:32:33.841+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:32:33.844+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:32:33.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:32:33.850+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:32:33.849+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:32:33.851+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:32:33.850+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:32:33.851+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:32:33.866+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-03-21T21:33:34.598+0000] {processor.py:186} INFO - Started process (PID=3757925) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:33:34.607+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T21:33:34.611+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:33:34.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:33:34.616+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:33:34.615+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T21:33:34.617+0000] {logging_mixin.py:190} INFO - [2025-03-21T21:33:34.617+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T21:33:34.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T21:33:34.632+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-03-21T22:19:52.172+0000] {processor.py:186} INFO - Started process (PID=3758888) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T22:19:52.181+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T22:19:52.184+0000] {logging_mixin.py:190} INFO - [2025-03-21T22:19:52.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T22:19:52.190+0000] {logging_mixin.py:190} INFO - [2025-03-21T22:19:52.189+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T22:19:52.190+0000] {logging_mixin.py:190} INFO - [2025-03-21T22:19:52.190+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T22:19:52.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T22:19:52.205+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-03-21T22:20:58.889+0000] {processor.py:186} INFO - Started process (PID=3759862) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T22:20:58.898+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T22:20:58.900+0000] {logging_mixin.py:190} INFO - [2025-03-21T22:20:58.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T22:20:58.903+0000] {logging_mixin.py:190} INFO - [2025-03-21T22:20:58.902+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T22:20:58.903+0000] {logging_mixin.py:190} INFO - [2025-03-21T22:20:58.903+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T22:20:58.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T22:20:58.911+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-03-21T22:22:00.064+0000] {processor.py:186} INFO - Started process (PID=3760714) to work on /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T22:22:00.073+0000] {processor.py:914} INFO - Processing file /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-21T22:22:00.075+0000] {logging_mixin.py:190} INFO - [2025-03-21T22:22:00.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T22:22:00.080+0000] {logging_mixin.py:190} INFO - [2025-03-21T22:22:00.079+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-21T22:22:00.081+0000] {logging_mixin.py:190} INFO - [2025-03-21T22:22:00.081+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-21T22:22:00.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-21T22:22:00.096+0000] {processor.py:208} INFO - Processing /home/usmail/sys_fraud/sys_detection_frauds/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
